##### Importações

In [2]:
import cv2, os, re
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Aprendizado de máquina com imagens
from sklearn import svm, metrics
from sklearn.model_selection import train_test_split
from sklearn.utils import Bunch

#### 2. Classificação de frutas

##### Carregando as 100 imagens: Item a

In [4]:
DB_PATH = 'images'

##### Obtendo os momentos da imagem: Item b

In [5]:
def build_file(path, file):
    return os.path.join(path, file)

In [6]:
morango_regex = '^morango*'
banana_regex  = '^banana*'

In [12]:
def gen_vector_moments_images(path):
    vector_moments = []
    for file in os.listdir(path):
        img = cv2.imread(
            build_file(path, file),0
        )
        moments = cv2.moments(img)
        vector_moments.append([moments[k] for k in moments.keys()])

    return np.array(vector_moments)

In [13]:
def create_target(path):
    vector_target = np.array([])
    for filename in os.listdir(path):
        if re.match(morango_regex, filename):
            vector_target = np.append(vector_target, 0)
        elif re.match(banana_regex, filename):
            vector_target = np.append(vector_target, 1)
    return vector_target

In [14]:
# Gerar Dataset de Imagens
dataset_frutas = gen_vector_moments_images(DB_PATH)

In [15]:
dataset_frutas

array([[ 1.60883420e+07,  2.61713105e+09,  3.38230255e+09, ...,
         2.66870773e-07, -8.54419500e-07,  5.38242600e-06],
       [ 7.44459900e+06,  1.07033435e+09,  6.44084442e+08, ...,
         1.59545449e-06, -9.19968603e-07,  1.92379281e-06],
       [ 9.28378200e+06,  1.43974659e+09,  9.27216191e+08, ...,
         5.86352656e-07, -1.45856230e-06,  3.46622525e-06],
       ...,
       [ 1.49083480e+07,  2.35371130e+09,  3.42113798e+09, ...,
        -9.26091319e-07, -1.56870784e-06, -2.55962133e-07],
       [ 1.06443110e+07,  1.61109462e+09,  1.90585182e+09, ...,
         1.55301436e-06,  1.98594210e-07,  8.92562215e-06],
       [ 5.61077700e+06,  8.13729682e+08,  5.56821060e+08, ...,
         1.77891577e-06, -9.73949899e-07,  2.68595600e-08]])

In [16]:
# Gerar saídas
alvos = create_target(DB_PATH)

##### Gerar matriz (100x25): Item c

In [17]:
nome_alvos = ['banana', 'morango']

In [18]:
data = Bunch(
    data=dataset_frutas,
    target=alvos.astype(int),
)

In [19]:
data.data

array([[ 1.60883420e+07,  2.61713105e+09,  3.38230255e+09, ...,
         2.66870773e-07, -8.54419500e-07,  5.38242600e-06],
       [ 7.44459900e+06,  1.07033435e+09,  6.44084442e+08, ...,
         1.59545449e-06, -9.19968603e-07,  1.92379281e-06],
       [ 9.28378200e+06,  1.43974659e+09,  9.27216191e+08, ...,
         5.86352656e-07, -1.45856230e-06,  3.46622525e-06],
       ...,
       [ 1.49083480e+07,  2.35371130e+09,  3.42113798e+09, ...,
        -9.26091319e-07, -1.56870784e-06, -2.55962133e-07],
       [ 1.06443110e+07,  1.61109462e+09,  1.90585182e+09, ...,
         1.55301436e-06,  1.98594210e-07,  8.92562215e-06],
       [ 5.61077700e+06,  8.13729682e+08,  5.56821060e+08, ...,
         1.77891577e-06, -9.73949899e-07,  2.68595600e-08]])

In [20]:
data.target

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##### Realizando Classificação (SVM): Item d

In [24]:
# Separar conjunto de teste e treino
X_train, X_test, y_train, y_test = train_test_split(
    data.data,
    data.target,
    test_size=0.8,
    random_state=100
)

In [25]:
X_train

array([[ 5.69377400e+06,  8.43210496e+08,  4.13702764e+08,
         1.70837545e+11,  6.83118306e+10,  4.34289167e+10,
         3.88836481e+13,  1.47214762e+13,  7.57471313e+12,
         5.25634604e+12,  4.59636145e+10,  7.04517116e+09,
         1.33697719e+10, -3.00874193e+10,  2.21938745e+11,
         1.19388783e+11,  1.57990174e+11,  1.41779592e-03,
         2.17315698e-04,  4.12404646e-04, -3.88941582e-07,
         2.86901331e-06,  1.54334480e-06,  2.04234693e-06],
       [ 7.29502500e+06,  1.21231590e+09,  7.39150561e+08,
         2.46175806e+11,  1.23029566e+11,  9.88895353e+10,
         5.52126236e+13,  2.50603397e+13,  1.63677527e+13,
         1.48272649e+13,  4.47083872e+10,  1.94622946e+08,
         2.39969130e+10, -5.57469327e+11,  5.24920917e+10,
        -1.05538070e+11, -5.53323588e+10,  8.40108608e-04,
         3.65713063e-06,  4.50922399e-04, -3.87841266e-06,
         3.65196761e-07, -7.34247010e-07, -3.84957002e-07],
       [ 8.06470700e+06,  1.18849769e+09,  8.08313201e

In [26]:
# Criando o Modelo Classificador
classificador = svm.SVC(kernel="linear")

In [27]:
# Treinamento do Modelo Classificador
classificador.fit(X_train, y_train)

In [22]:
# Predição Teste do Modelo (dados de entrada)
pred = classificador.predict(X_test)

In [25]:
# Métricas de Avaliação
accuracy  = metrics.accuracy_score(y_test,pred)
precision = metrics.precision_score(y_test,pred)
recall    = metrics.recall_score(y_test, pred)
f1        = metrics.f1_score(y_test, pred)
report    = metrics.classification_report(y_test, pred)

In [26]:
print('Accuracy:  ', accuracy)
print('Precision: ', precision)
print('Recall:    ', recall)
print('F1 Score:  ', f1)

Accuracy:   0.5185185185185185
Precision:  0.5454545454545454
Recall:     0.2222222222222222
F1 Score:   0.3157894736842105


In [27]:
report

'              precision    recall  f1-score   support\n\n           0       0.51      0.81      0.63        54\n           1       0.55      0.22      0.32        54\n\n    accuracy                           0.52       108\n   macro avg       0.53      0.52      0.47       108\nweighted avg       0.53      0.52      0.47       108\n'